server:
  port: 6300
  shutdown: graceful


spring:
  application:
    name: lck-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: lck-service
          uri: http://172.20.0.6:17001/
          predicates:
            - Path=/lck-service/**
#          filters:
#            - CustomFilter

management:
  endpoint:
    web:


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@172.20.0.7:22301/eureka/
    instance:
      hostname: ${spring.application.name}:${spring.application.instance_id:${random.value}}}